---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - bennewton999@gmail.com
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export CI=false
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: ["master"]